### ISSUE TITLE
100% cpu

### ISSUE THREAD

**Issue by RageYL** [zchee/deoplete-jedi#132]
# Problem summary

When editing the following file, i get 100% cpu usage (for people like me who have some python plugins that use synchronous functions, neovim freeze forever)

```python
#!/usr/bin/env python3

"""
./A.B
"""

"""
import C
"""
```

## Expected
normal completion, no 100% cpu usage

## Environment Information

 * OS: archlinux
 * Neovim version: NVIM v0.2.1-870-g1551f7132

## Provide a minimal init.vim with less than 50 lines (required)

```vim
let s:config_dir = expand('~/.config/nvim/')
let s:bundle_dir = s:config_dir . '/bundle/'

call plug#begin(s:bundle_dir)

Plug 'zchee/deoplete-jedi'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

let g:deoplete#enable_at_startup = 1
```

## Steps to reproduce the issue after starting Neovim (required)

 /B\<CR>s

Without the import part, everything works fine (i don't understand anything that is happening...)

**Comment by blueyed** [comment]
Sounds like a bug fixed in Jedi by now (hopefully).
You might want to try the branch from https://github.com/zchee/deoplete-jedi/pull/131.

**Comment by RageYL** [comment]
I did the following:

```
git fetch origin pull/131/head:jedi-parso
git checkout jedi-parso

vim +PlugUpdate
```

still the same issue, am i missing a step ?

**Comment by blueyed** [comment]
Check the version(s) reported in `:JediDebugInfo`.

**Comment by blueyed** [comment]
(it was just a guess though - might still be an issue of course)
(thanks for trying!)

**Comment by RageYL** [comment]
Just noticed i forgot to do:

```
git submodule update --init
```

but still doesn't change anything. 

I don't have a JediDebugInfo command :s

**Comment by blueyed** [comment]
> I don't have a JediDebugInfo command :s

Oh, sorry - that comes with jedi-vim.  Nevermind - or you could try if it fails there, too (with both old and new jedi - also a submodule there).
In that case it is certainly a Jedi issue, and it would be good to have a failing test case using jedi's `Script`.

**Comment by RageYL** [comment]
I just tried with jedi-vim: i couldn't reproduce the issue (i only tested with the latest version). so seems to me like an issue with deoplete or deoplete-jedi.

**Comment by blueyed** [comment]
Ok, thanks for reporting back.
Then we need some more information or somebody to investigate based on your report / provided information.

**Comment by RageYL** [comment]
I won't have the time nor the knowledge to look at deoplete-jedi sources, but if you need me to run more tests, i'll be happy to help =)

**Comment by blueyed** [comment]
I think it might be possible to reproduce, but do not have the time myself currently.

**Comment by Shougo** [comment]
Reproduced the problem.
I will research it.

**Comment by Shougo** [comment]
I have researched.
`utils.module_search()` is freezing.

**Comment by zchee** [comment]
@Shougo 🙇

**Comment by Shougo** [comment]
`utils.module_file()` seems infinite loop.
I will fix it if possible.

**Comment by Shougo** [comment]
I will send the PR.  Please wait.

**Comment by Shougo** [comment]
Done.
